runtime: nodejs
env: standard

service: green-api-interface

automatic_scaling:
  min_instances: 1
  max_instances: 1

env_variables:
  NODE_ENV: production

handlers:
- url: /.*
  script: auto
  secure: always

health_check:
  enable_health_check: False

readiness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2