runtime: nodejs
env: standard

service: green-api-interface

automatic_scaling:
  min_instances: 1
  max_instances: 3

env_variables:
  NODE_ENV: production

handlers:
- url: /.*
  script: auto
  secure: always

health_check:
  enable_health_check: True
  check_interval_sec: 30
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2